# Generated by Django 3.1.6 on 2021-04-06 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=7)),
                ('subject_name', models.CharField(max_length=120)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('department', models.CharField(max_length=100)),
                ('syllabus', models.TextField(blank=True)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ltp', models.CharField(max_length=10)),
                ('credit', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subject',
                'managed': True,
                'unique_together': {('subject_code', 'semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('is_recurring', models.BooleanField(default=False)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('time_of_edit', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegisteredSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registered_subjects',
                'managed': True,
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('time_of_edit', models.DateTimeField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('event_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
                'managed': True,
                'unique_together': {('time_of_edit', 'user')},
            },
        ),
    ]
