# Generated by Django 3.1.6 on 2021-04-01 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institute_email_id',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Institite email must end with @iitkgp.ac.in', regex='.+@iitkgp.ac.in')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
