# Generated by Django 3.1.6 on 2021-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
